---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flover
  namespace: default
  labels:
    app: flover
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flover
  template:
    metadata:
      labels:
        app: flover
    spec:
      containers:
        - name: web
          image: gcr.io/flover-mascots-1/flover
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/flover
      volumes:
        - name: datasources
          configMap:
            name: datasources
---
apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: flover
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
  labels:
    app: flover
spec:
  scaleTargetRef:
    kind: Deployment
    name: flover
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
